import image1 from "./images/manKurta/kurta17.jpeg";
import image2 from "./images/manKurta/kurta15.jpg";

const Mans = [
  {
    ID: "101",
    Category: "Men Kurtas",
    Title: "Cotton Printed Kurta",
    Description:
      "A comfortable cotton kurta perfect for casual and festive occasions.",
    MainImage: image1,
    Size: ["S", "M", "L", "XL"],
    Discount: "10%",
    Offer: "Buy 1 Get 1 Free",
    Price: "399",
    Brand: "FabIndia",
    Bandwidth: "Regular",
    Color: "White",
    Pattern: "Printed",
    Length: "Knee-Length",
  },
  {
    ID: "102",
    Category: "Men Kurtas",
    Title: "Silk Embroidered Kurta",
    Description:
      "Elegant silk kurta with intricate embroidery for weddings and festive events.",
    MainImage: image2,
    Size: ["M", "L", "XL"],
    Discount: "50%",
    Offer: "Flat ₹1500 Off",
    Price: "1399",
    Brand: "Manyavar",
    Bandwidth: "Slim",
    Color: "Blue",
    Pattern: "Embroidered",
    Length: "Long",
  },
  {
    ID: "102",
    Category: "Men Kurtas",
    Title: "Silk Embroidered Kurta",
    Description:
      "Elegant silk kurta with intricate embroidery for weddings and festive events.",
    MainImage: image2,
    Size: ["M", "L", "XL"],
    Discount: "50%",
    Offer: "Flat ₹1500 Off",
    Price: "1399",
    Brand: "Manyavar",
    Bandwidth: "Slim",
    Color: "Blue",
    Pattern: "Embroidered",
    Length: "Long",
  },
  {
    ID: "102",
    Category: "Men Kurtas",
    Title: "Silk Embroidered Kurta",
    Description:
      "Elegant silk kurta with intricate embroidery for weddings and festive events.",
    MainImage: image2,
    Size: ["M", "L", "XL"],
    Discount: "50%",
    Offer: "Flat ₹1500 Off",
    Price: "1399",
    Brand: "Manyavar",
    Bandwidth: "Slim",
    Color: "Blue",
    Pattern: "Embroidered",
    Length: "Long",
  },
  {
    ID: "102",
    Category: "Men Kurtas",
    Title: "Silk Embroidered Kurta",
    Description:
      "Elegant silk kurta with intricate embroidery for weddings and festive events.",
    MainImage: image2,
    Size: ["M", "L", "XL"],
    Discount: "50%",
    Offer: "Flat ₹1500 Off",
    Price: "1399",
    Brand: "Manyavar",
    Bandwidth: "Slim",
    Color: "Blue",
    Pattern: "Embroidered",
    Length: "Long",
  },
  {
    ID: "102",
    Category: "Men Kurtas",
    Title: "Silk Embroidered Kurta",
    Description:
      "Elegant silk kurta with intricate embroidery for weddings and festive events.",
    MainImage: image2,
    Size: ["M", "L", "XL"],
    Discount: "50%",
    Offer: "Flat ₹1500 Off",
    Price: "1399",
    Brand: "Manyavar",
    Bandwidth: "Slim",
    Color: "Blue",
    Pattern: "Embroidered",
    Length: "Long",
  },
];

// const Womans = [];
export default Mans;
